syntax = "proto3";

import "google/protobuf/timestamp.proto";

option csharp_namespace = "GrpcServiceShipTelemetry";

package greet;

service ShipTelemetryService {
  rpc RegisterTelemetryDataStream (stream TelemetryData) returns (stream TelemetryResponse);
  rpc GetTelemetryData (TelemetryRequest) returns (GetTelemetryResponse);
}

message TelemetryData {
  string shipId = 1;
  double latitude = 2;
  double longitude = 3;
  double speed = 4;
  google.protobuf.Timestamp timestamp = 5;
}

message TelemetryRequest {
  string shipId = 1;
}

message TelemetryResponse {
  bool success = 1;
  string message = 2;
  google.protobuf.Timestamp receivedAt = 3;
}

message GetTelemetryResponse {
  string message = 1;
  TelemetryData data = 2;
}
